endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

zuul:
  routes:
    workspaces-api: /workspaces-service/**
    employees-api: /employees-service/**